// constants.dart

final Map<String, List<String>> fruitAdvantages = {
  'tomato':[
    'NUTRITIONAL VALUES per 100 g:',
    'Calories: 18 kcal',
    'Carbohydrates: 3.9 g',
    'Fiber: 1.2 g',
    'Vitamin C: 14.7 mg',
    'Vitamin A: 833 IU',
    'Potassium: 237 mg \n',
    'BENEFITS:',
    'Rich in vitamin C and potassium',
    'Contains lycopene, an antioxidant linked to various health benefits',
    'Supports heart health and may reduce the risk of certain cancers \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals with nightshade plant allergies should limit tomato consumption due to potential allergic reactions'
  ],
  'pumpkin':[
    'NUTRITIONAL VALUES per 100 g:',
    'Calories: 26 kcal',
    'Carbohydrates: 6.5 g',
    'Fiber: 0.5g',
    'Vitamin A: 7384 IU',
    'Vitamin C: 9 mg',
    'Potassium: 340 mg \n',
    'BENEFITS:',
    'High in vitamin A and potassium',
    'Good source of fiber for digestive health',
    'Contains antioxidants that support eye health \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Those with diabetes should monitor portions due to its carbohydrate content'
  ],
  'bean':[
    'NUTRITIONAL VALUES per cup, cooked (177 g):',
    'Calories: 160',
    'Protein: 15 grams',
    'Dietary fiber: 13 grams',
    'Folate: 256 micrograms',
    'Iron: 3 milligrams \n',
    'BENEFITS:',
    'High in protein and fiber for satiety and digestive health',
    'Rich source of folate for cell growth and development',
    'Contains iron for energy production and oxygen transport \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'People with irritable bowel syndrome (IBS) may need to limit bean intake due to their high fermentable oligosaccharides content, which can worsen symptoms in some individuals'
  ],
   'carrot':[
    'NUTRITIONAL VALUES per medium carrot (61 g):',
    'Calories: 25 kcal',
    'Carbohydrates: 6 g ',
    'Fiber: 1 g',
    'Vitamin A: 10191 IU',
    'Vitamin K: 8 mcg \n',
    'BENEFITS:',
    'Excellent source of beta-carotene for eye health',
    'Provides fiber for digestive health',
    'Rich in vitamins like vitamin A and vitamin K \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Those prone to kidney stones may need to moderate carrot consumption due to its oxalate content, which can contribute to stone formation'
  ],
  'cucumber':[
    'NUTRITIONAL VALUES per cup (104 g):',
    'Calories: 16 kcal',
    'Carbohydrates: 3.8 g',
    'Fiber: 0.6 g',
    'Vitamin K: 10.2 mcg',
    'Vitamin C: 2.4 mg \n',
    'BENEFITS:',
    'Hydrating and low in calories',
    'Contains antioxidants that promote skin health',
    'Provides some essential vitamins like vitamin K and vitamin C \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals with kidney issues may need to limit cucumber intake due to its potential impact on electrolyte balance'
  ],
   'cabbage':[
    'NUTRITIONAL VALUES per (177 g):',
    'Calories: 160',
    'Protein: 15 grams',
    'Dietary fiber: 13 grams',
    'Folate: 256 micrograms',
    'Iron: 3 milligrams \n',
    'BENEFITS:',
    'Rich in fiber for digestive health',
    'Contains vitamin K for bone health',
    'Low in calories but high in nutrients like vitamin C \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Those with thyroid issues may need to moderate cabbage consumption as it contains compounds that can interfere with thyroid function when consumed excessively',
  ],
  'capsicum':[
    'NUTRITIONAL VALUES per medium pepper (119 g):',
    'Calories: 30 kcal',
    'Carbohydrates: 7 g',
    'Fiber: 2 g',
    'Vitamin C: 152 mg \n',
    'BENEFITS:',
    'High in vitamin C and antioxidants',
    'Contains vitamin K for bone health',
    'May aid in weight management due to its low calorie content \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals with gastrointestinal conditions like acid reflux may need to limit capsicum intake as it can exacerbate symptoms',
  ],
    'papaya':[
    'NUTRITIONAL VALUES per 100 g:',
    'Calories: 43 kcal',
    'Carbohydrates: 11 g',
    'Fiber: 1.7 g',
    'Vitamin C: 60.9 mg',
    'Vitamin A (as beta-carotene): 2764 IU \n',
    'BENEFITS:',
    'Rich in vitamin C and beta-carotene',
    'Contains enzymes that aid digestion',
    'Supports skin health and immune function \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'People on blood-thinning medications should consume papaya in moderation due to its vitamin K content, which can interfere with blood clotting',
  ],
   'potato':[
    'NUTRITIONAL VALUES per 100 g:',
    'Calories: 77 kcal',
    'Carbohydrates: 17 g',
    'Fiber: 2.2 g',
    'Vitamin C: 19.7 mg',
    'Potassium: 421 mg \n',
    'BENEFITS:',
    'Good source of vitamin C and potassium',
    'Provides energy from carbohydrates',
    'Contains fiber for digestive health \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals with diabetes should be cautious due to the high glycemic index of potatoes, which can affect blood sugar levels.',
  ],
   'kiwi':[
    'NUTRITIONAL VALUES per 76 g:',
    'Calories: 46 kcal',
    'Carbohydrates: 11 g',
    'Sugars: 6 g',
    'Dietary Fiber: 2 g',
    'Protein: 1 g',
    'Vitamin C: 71 mg \n',
    'BENEFITS:',
    'High in Vitamin C, aiding collagen production for skin health',
    'Good source of fiber and antioxidants promoting heart health',
    'Contains serotonin helping improve sleep quality \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals allergic to latex may also be allergic to kiwi due to cross-reactivity',
  ],
   'cherry':[
    'NUTRITIONAL VALUES:',
    'Calories: 87',
    'Protein: 1.6 g',
    'Fat: 0.5 g',
    'Carbohydrates: 22 g',
    'Fiber: 3 g',
    'Vitamin C: 16% of the Daily Value (DV)',
    'Potassium: 9% of the DV \n',
    'BENEFITS:',
    'Antioxidant Properties: are rich in antioxidants like anthocyanins and quercetin, which help reduce inflammation and oxidative stress in the body',
    'Improved Sleep: Cherries contain melatonin, a hormone that regulates sleep-wake cycles, making them a natural remedy for improving sleep quality',
    'Heart Health: The potassium content in cherries can help regulate blood pressure levels, while the fiber content supports heart health by lowering cholesterol levels \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals who need to monitor their blood sugar levels should consume cherries in moderation due to their natural sugar content',
  ],
  'orange':[
    'NUTRITIONAL VALUES:',
    'Calories: 43 kcal in 100g of oranges',
    'Carbohydrates: 8.3 g',
    'Sugars: 8.2 g',
    'Dietary Fiber: 2.4 g',
    'Protein: 1 g',
    'Vitamin C: 53.2 mg \n',
    'BENEFITS:',
    'Rich in Vitamin C, which boosts the immune system',
    'Contains antioxidants that help protect cells from damage',
    'Good source of fiber, promoting digestive health \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals with gastroesophageal reflux disease (GERD) should limit acidic fruits like oranges',
  ],
    'banana':[
    'NUTRITIONAL VALUES:',
    'Calories: 95.3 kcal in a medium banana (100g)',
    'Carbohydrates: 25 g',
    'Sugars: 14 g',
    'Dietary Fiber: 3.1 g',
    'Protein: 1.3 g',
    'Vitamin C: 8.7 mg \n',
    'BENEFITS:',
    'Excellent source of potassium for heart health',
    'Contains vitamin B6 for energy production',
    'Natural prebiotic properties promoting gut health \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals with kidney issues may need to limit bananas due to their potassium content',
  ],
    'chikoo':[
    'NUTRITIONAL VALUES:',
    'Calories: 218 kcal',
    'Protein: 1.4 g',
    'Fat: 0.6 g',
    'Carbohydrates: 57 g',
    'Fiber: 5.3 g',
    'Vitamin C: 23% of the DV',
    'Vitamin A: 2% of the DV \n',
    'BENEFITS:',
    'Digestive Health: Chikoos are rich in dietary fiber, which aids digestion and helps prevent constipation',
    'Boosted Immunity: The vitamin C content in chikoos supports a healthy immune system and helps the body fight off infections',
    'Skin Health: The antioxidants present in chikoos can help protect the skin from damage caused by free radicals, promoting healthier skin \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals with diabetes should be cautious when consuming chikoos due to their relatively high sugar content',
  ],
   'strawberry':[
    'NUTRITIONAL VALUES:',
    'Calories: 50 kcal in serving (152g) of strawberries',
    'Carbohydrates: 11 g',
    'Sugars: 7 g',
    'Dietary Fiber: 3 g',
    'Protein: 1 g',
    'Vitamin C: 97 mg \n',
    'BENEFITS:',
    'Rich in Vitamin C and manganese for immune support',
    'Contains antioxidants like ellagic acid linked to cancer prevention',
    'Low in calories but high in nutrients like folate and potassium \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Those with a history of kidney stones may need to moderate strawberry intake due to their oxalate content',
  ],
  'mango':[
    'NUTRITIONAL VALUES:',
    'Calories: 60 kcal in 100g of mango',
    'Carbohydrates: 15 g',
    'Sugars: 14 g',
    'Dietary Fiber: 1.6 g',
    'Protein: 0.8 g',
    'Vitamin C: 36.4 mg \n',
    'BENEFITS:',
    'High in Vitamin A, aiding vision and skin health',
    'Contains enzymes that aid digestion',
    'Rich in antioxidants like quercetin, isoquercitrin, astragalin, and fisetin \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Diabetics should consume mango in moderation due to its natural sugar content',
  ],
    'apple':[
    'NUTRITIONAL VALUES:',
    'Calories: 89.3 kcal in a medium apple (182g)',
    'Carbohydrates: 22.9 g',
    'Sugars: 19 g',
    'Dietary Fiber: 4 g',
    'Protein: 0 g',
    'Vitamin C: 8.4 mg\n',
    'BENEFITS:',
    'High in fiber aiding digestion and promoting satiety',
    'Contains antioxidants like quercetin reducing inflammation',
    'May help lower cholesterol levels and reduce the risk of heart disease \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'People with irritable bowel syndrome (IBS) may need to limit apple consumption due to its high fiber content',
  ],
   'grapes':[
    'NUTRITIONAL VALUES:',
    'Calories: 62 kcal in serving 92g of grapes',
    'Carbohydrates: 16 g',
    'Sugars: 15 g',
    'Dietary Fiber: 1 g',
    'Protein: 0 g',
    'Vitamin C: 4 mg\n',
    'BENEFITS:',
    'Rich in antioxidants like resveratrol linked to heart health benefits',
    'Good source of vitamins C and K',
    'May help improve brain function and reduce the risk of chronic diseases \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'People with diabetes should monitor their intake as grapes are high in natural sugars',
  ],
  'brinjal':[
    'NUTRITIONAL VALUES per cup, cubed (82 g):',
    'Calories: 25 kcal',
    'Carbohydrates: 4.9 g ',
    'Fiber: 1.8 g',
    'Folate: 15 mcg',
    'Protein: 0 g',
    'Potassium: 122 mg \n',
    'BENEFITS:',
    'Good source of fiber for digestive health',
    'Contains antioxidants that support overall well-being',
    'Provides essential minerals like potassium \n',
    'PATIENTS TO LIMIT CONSUMPTION:',
    'Individuals sensitive to histamine may need to limit brinjal consumption as it can trigger allergic reactions in some cases',
  ],
  
  
};
